# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    loaders:
        default:
            flysystem:
                filesystem_service: default.storage

    filter_sets:
        thumbnail:
            quality: 90
            filters:
                thumbnail: { size: [45, 45], mode: outbound }
