security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\AdminUser: 'sodium'

    role_hierarchy:
        ROLE_ADMIN:           [ ROLE_USER ]

    providers:
        admin_entity_provider:
            entity:
                class: App\Entity\AdminUser
                property: email

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false

        admin:
            login_throttling: ~
            pattern: ^/
            user_checker: Umbrella\AdminBundle\Security\UserChecker
            entry_point: Umbrella\AdminBundle\Security\AuthenticationEntryPoint
            provider: admin_entity_provider
            lazy: true
            form_login:
                login_path: umbrella_admin_login
                check_path: umbrella_admin_login
                default_target_path: app_default_index
                enable_csrf: true
            logout:
                path: umbrella_admin_logout
                target: umbrella_admin_login
