umbrella_admin:
  app_name: "Umbrella Admin"
  menu: App\Menu\AdminMenu
  notification:
    provider: App\Notification\AdminNotificationProvider
    poll_interval: 2
  user:
    class: App\Entity\AdminUser

