umbrella_admin:
  home_route: app_admin_default_index
  theme:
    name: "Admin"
    icon: "mdi mdi-umbrella"
  assets:
    script_entry: admin
    stylesheet_entry: admin
  notification:
    provider: App\Notification\NotificationProvider
    poll_interval: 10

