umbrella_admin:
  app_name: "Admin"
  menu:
    options:
      logo_route: app_admin_default_index
  assets:
    script_entry: admin
    stylesheet_entry: admin
  notification:
    provider: App\Notification\NotificationProvider
    poll_interval: 10
  user:
    class: App\Entity\AdminUser

