admin_user_:
  resource: "@UmbrellaAdminBundle/config/routes/user.yaml"
  prefix: /admin

admin_userprofile_:
  resource: "@UmbrellaAdminBundle/config/routes/user_profile.yaml"
  prefix: /admin

admin_notification_:
  resource: "@UmbrellaAdminBundle/config/routes/notification.yaml"
  prefix: /admin