umbrella_file_:
  resource: "@UmbrellaCoreBundle/src/Controller/UmbrellaFileController.php"
  type: annotation
  prefix: /download

umbrella_admin_:
  resource: "@UmbrellaAdminBundle/config/routing.yml"
  prefix: /admin

app_:
  resource: "../src/Controller/"
  type: annotation
  prefix: /

admin_:
  resource: "../src/Controller/Admin/"
  type: annotation
  prefix: /admin