umbrella2:
    children:
        about:
            icon: mdi mdi-lifebuoy
            route: app_admin_default_about

theme:
    children:
        icon:
            icon: uil-streering
            children:
                icon_md:
                    route: app_admin_icon_md
                icon_unicon:
                    route: app_admin_icon_unicon

symfony_components:
    children:
        messenger:
            icon: uil-process
            route: app_admin_message_index

umbrella_components:
    children:
        datatables:
            icon: uil-table
            children:
                simple_datatable:
                    route: app_admin_datatable_simple
                multiple_datatable:
                    route: app_admin_datatable_multiple
                api_datatable:
                    route: app_admin_datatable_api
                tree_datatable:
                    route: app_admin_datatable_tree
                export_datatable:
                    route: app_admin_datatableexport_index

        js_response:
            icon: uil-exchange
            route: app_admin_jsresponse_index

        forms:
            icon: uil-document-layout-center
            route: app_admin_form_base

        toast:
            icon: uil-chat
            route: app_admin_toast_index

        menu:
            icon: uil-bars
            route: app_admin_menu_howto

        notification:
            icon: uil-bell
            route: app_admin_notification_howto

        tabs:
            icon: uil-layers-alt
            route: app_admin_tabs_index

        file:
            icon: uil-file-upload-alt
            route: app_admin_file_index

other:
    children:
        umbrella_maker:
            icon: mdi mdi-console-line
            route: app_admin_maker_index
        umbrella_config:
            icon: mdi mdi-cogs
            route: app_admin_umbrellaconfig_index
admin:
    children:
        users:
            icon: uil-user
            route: umbrella_admin_user_index

        groups:
            icon: uil-users-alt
            route: umbrella_admin_usergroup_index
