umbrella:
    children:
        about:
            icon: mdi mdi-lifebuoy
            route: app_admin_default_about

        datatable:
            icon: uil-table
            children:
                basic:
                    route: app_admin_datatable_basic
                custom_adapter:
                    route: app_admin_datatable_customadapter
                draggable:
                    route: app_admin_datatable_draggable
                editable:
                    route: app_admin_datatable_editable
                multiple:
                    route: app_admin_datatable_multiple
                modal:
                    route: app_admin_datatable_modal
                tree:
                    route: app_admin_datatable_tree

        forms:
            icon: uil-document-layout-center
            route: app_admin_form_index

        js_response:
            icon: uil-exchange
            route: app_admin_js_index

        menu:
            icon: uil-bars
            route: app_admin_menu_index


        notification:
            icon: uil-bell
            route: app_admin_notification_index

        tabs:
            icon: uil-layers-alt
            route: app_admin_tabs_index

advanced:
    children:
        config_reference:
            icon: mdi mdi-cogs
            route: app_admin_umbrellaconfig_index
admin:
    children:
        users:
            icon: uil-user
            route: umbrella_admin_user_index