name: Deploy app
on: [push]

jobs:
    deploy-project:
        name: Deploy app
        runs-on: ubuntu-20.04
        steps:
            # Checkout
            - name: Checkout
              uses: actions/checkout@v2
